spring.application.name=StageLink_back
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.eu-paris-1.oraclecloud.com))(connect_data=(service_name=g1303514a77bafc_stagelink_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.username=ADMIN
spring.datasource.password=RaisRajat123

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000

#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=WKSP_SI

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


# Oracle Object Storage
oci.tenancy.ocid=ocid1.tenancy.oc1..aaaaaaaas6s7zvsmajpng6utzwgoasv667a4q6j2l3qdotgtojrj4lnxpxia
oci.user.ocid=ocid1.user.oc1..aaaaaaaauuwgqsxxllcti4cgraktdg3oqh5gc26tts37ehwex5pm72gy3dxa
oci.fingerprint=18:36:16:90:9a:f6:a5:71:fc:1f:da:ed:1c:48:c4:d4
oci.region=eu-paris-1
oci.api.key.file=src/main/resources/static/oci_api_key.pem
oci.bucket.name=StageLink
oci.namespace=ax35idwc39uf

oci.storage.auth-token=96<1k{NC0M:MiIncsnUt
oci.storage.endpoint=https://objectstorage.eu-paris-1.oraclecloud.com

oci.config.path=config
oci.config.profile=DEFAULT

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

